import React, { useState, useEffect } from 'react';
import { ChevronRight, ChevronLeft, RotateCcw, Trophy, Book, Check, X, Volume2 } from 'lucide-react';

const names = [
  { id: 1, telugu: "స్కందాయ", english: "Skandaya", meaningTelugu: "వేగవంతుడు, కార్తికేయుడు", meaningEnglish: "The swift one, Lord Kartikeya" },
  { id: 2, telugu: "గుహాయ", english: "Guhaya", meaningTelugu: "గుహలో నివసించేవాడు, రహస్యమైనవాడు", meaningEnglish: "One who dwells in caves, the mysterious one" },
  { id: 3, telugu: "షణ్ముఖాయ", english: "Shanmukhaya", meaningTelugu: "ఆరు ముఖాలు కలవాడు", meaningEnglish: "The six-faced one" },
  { id: 4, telugu: "ఫాలనేత్రసుతాయ", english: "Phalanetra Suthaya", meaningTelugu: "నుదిటి నేత్రం కలిగిన శివుని కుమారుడు", meaningEnglish: "Son of the one with the eye on the forehead (Shiva)" },
  { id: 5, telugu: "ప్రభవే", english: "Prabhave", meaningTelugu: "శక్తివంతుడు, ప్రభువు", meaningEnglish: "The powerful one, the Lord" },
  { id: 6, telugu: "పింగళాయ", english: "Pingalaya", meaningTelugu: "ఎరుపు రంగు కలవాడు", meaningEnglish: "One with reddish-brown complexion" },
  { id: 7, telugu: "కృత్తికాసూనవే", english: "Kruttika Sunave", meaningTelugu: "కృత్తికా దేవతల కుమారుడు", meaningEnglish: "Son of the Krittikas (six divine mothers)" },
  { id: 8, telugu: "శిఖివాహాయ", english: "Sikhi Vahanaya", meaningTelugu: "నెమలి వాహనం కలవాడు", meaningEnglish: "One who rides a peacock" },
  { id: 9, telugu: "ద్విషడ్భుజాయ", english: "Dwishad Bhujaya", meaningTelugu: "పన్నెండు చేతులు కలవాడు", meaningEnglish: "One with twelve arms" },
  { id: 10, telugu: "ద్విషణ్ణేత్రాయ", english: "Dwishan Netraya", meaningTelugu: "పన్నెండు కన్నులు కలవాడు", meaningEnglish: "One with twelve eyes" },
  { id: 11, telugu: "శక్తిధరాయ", english: "Sakthidharaya", meaningTelugu: "శక్తి ఆయుధం ధరించినవాడు", meaningEnglish: "Bearer of the divine spear (Vel)" },
  { id: 12, telugu: "పిశితాశప్రభంజనాయ", english: "Pishitasha Prabhanjanaya", meaningTelugu: "పిశాచాలను నాశనం చేసేవాడు", meaningEnglish: "Destroyer of flesh-eating demons" },
  { id: 13, telugu: "తారకాసురసంహర్త్రే", english: "Tarakasura Samharthye", meaningTelugu: "తారకాసురుడిని సంహరించినవాడు", meaningEnglish: "Slayer of demon Tarakasura" },
  { id: 14, telugu: "రక్షోబలవిమర్దనాయ", english: "Rakshobhala Vimardhanaya", meaningTelugu: "రాక్షసుల సైన్యాన్ని నాశనం చేసేవాడు", meaningEnglish: "Destroyer of demon armies" },
  { id: 15, telugu: "మత్తాయ", english: "Matthaya", meaningTelugu: "ఆనందంతో మత్తుడైనవాడు", meaningEnglish: "The one intoxicated with bliss" },
  { id: 16, telugu: "ప్రమత్తాయ", english: "Pramatthaya", meaningTelugu: "అత్యంత ఆనందవంతుడు", meaningEnglish: "The extremely joyful one" },
  { id: 17, telugu: "ఉన్మత్తాయ", english: "Unmatthaya", meaningTelugu: "దివ్య ఆనందంతో నిండినవాడు", meaningEnglish: "Filled with divine ecstasy" },
  { id: 18, telugu: "సురసైన్యస్సురక్షకాయ", english: "Surasainya Surakshakaya", meaningTelugu: "దేవతల సైన్యాన్ని రక్షించేవాడు", meaningEnglish: "Protector of the army of gods" },
  { id: 19, telugu: "దేవసేనాపతయే", english: "Devasena-pathaye", meaningTelugu: "దేవతల సేనాధిపతి", meaningEnglish: "Commander of the celestial army" },
  { id: 20, telugu: "ప్రాజ్ఞాయ", english: "Pragnyaya", meaningTelugu: "జ్ఞానవంతుడు", meaningEnglish: "The wise one" },
  { id: 21, telugu: "కృపాళవే", english: "Krupalave", meaningTelugu: "కరుణామయుడు", meaningEnglish: "The compassionate one" },
  { id: 22, telugu: "భక్తవత్సలాయ", english: "Bhaktha Vatsalaya", meaningTelugu: "భక్తులను ప్రేమించేవాడు", meaningEnglish: "Lover of devotees" },
  { id: 23, telugu: "ఉమాసుతాయ", english: "Umasuthaya", meaningTelugu: "ఉమాదేవి కుమారుడు", meaningEnglish: "Son of Uma (Parvati)" },
  { id: 24, telugu: "శక్తిధరాయ", english: "Sakthidaraya", meaningTelugu: "శక్తిని ధరించినవాడు", meaningEnglish: "Bearer of divine power" },
  { id: 25, telugu: "కుమారాయ", english: "Kumuraya", meaningTelugu: "యువరాజు, శాశ్వత యువకుడు", meaningEnglish: "The eternal youth, the prince" },
  { id: 26, telugu: "క్రౌంచదారణాయ", english: "Krauncha Dharanaya", meaningTelugu: "క్రౌంచ పర్వతాన్ని చీల్చినవాడు", meaningEnglish: "One who split the Krauncha mountain" },
  { id: 27, telugu: "సేనాన్యే", english: "Senanye", meaningTelugu: "సైన్యాధిపతి", meaningEnglish: "Commander of armies" },
  { id: 28, telugu: "అగ్నిజన్మనే", english: "Agni Janmaney", meaningTelugu: "అగ్ని నుండి జన్మించినవాడు", meaningEnglish: "Born from fire" },
  { id: 29, telugu: "విశాఖాయ", english: "Vishakaya", meaningTelugu: "విశాఖ నక్షత్రం పాలకుడు", meaningEnglish: "Lord of Vishakha star" },
  { id: 30, telugu: "శంకరాత్మజాయ", english: "Sankaratmajaya", meaningTelugu: "శంకరుని కుమారుడు", meaningEnglish: "Son of Shankara (Shiva)" },
  { id: 31, telugu: "శివస్వామినే", english: "Siva Swamine", meaningTelugu: "శివ స్వరూపుడు", meaningEnglish: "Embodiment of Shiva" },
  { id: 32, telugu: "గణస్వామినే", english: "Jana Swamine", meaningTelugu: "గణాలకు అధిపతి", meaningEnglish: "Lord of divine beings" },
  { id: 33, telugu: "సర్వస్వామినే", english: "Sarwa Swamine", meaningTelugu: "సర్వులకు ప్రభువు", meaningEnglish: "Lord of all" },
  { id: 34, telugu: "సనాతనాయ", english: "Sanathanaya", meaningTelugu: "శాశ్వతమైనవాడు", meaningEnglish: "The eternal one" },
  { id: 35, telugu: "అనంతశక్తయే", english: "Anantha Sakthaye", meaningTelugu: "అనంత శక్తి కలవాడు", meaningEnglish: "Possessor of infinite power" },
  { id: 36, telugu: "అక్షోభ్యాయ", english: "Akshobhyaya", meaningTelugu: "కదల్చలేని, స్థిరమైనవాడు", meaningEnglish: "The unshakeable one" },
  { id: 37, telugu: "పార్వతీప్రియనందనాయ", english: "Parvathi Priya Nandanaya", meaningTelugu: "పార్వతీ దేవికి ప్రియమైన కుమారుడు", meaningEnglish: "Dear son of Parvati" },
  { id: 38, telugu: "గంగాసుతాయ", english: "Ganga Suthaya", meaningTelugu: "గంగా దేవి కుమారుడు", meaningEnglish: "Son of Ganga" },
  { id: 39, telugu: "శరోద్భూతాయ", english: "Sarod Bhootaya", meaningTelugu: "సరస్సు నుండి ఉద్భవించినవాడు", meaningEnglish: "One born from the reeds" },
  { id: 40, telugu: "ఆహూతాయ", english: "Aahutaya", meaningTelugu: "ఆహ్వానించబడినవాడు", meaningEnglish: "The invoked one" },
  { id: 41, telugu: "పావకాత్మజాయ", english: "Pavakathmajaya", meaningTelugu: "అగ్నికి కుమారుడు", meaningEnglish: "Son of fire god" },
  { id: 42, telugu: "జృంభాయ", english: "Jrumbhaya", meaningTelugu: "విస్తరించేవాడు", meaningEnglish: "The expanding one" },
  { id: 43, telugu: "ప్రజృంభాయ", english: "Prajrumbhaya", meaningTelugu: "గొప్పగా విస్తరించేవాడు", meaningEnglish: "The greatly expanding one" },
  { id: 44, telugu: "ఉజ్జృంభాయ", english: "Ujrumbhaya", meaningTelugu: "ఉన్నతంగా విస్తరించేవాడు", meaningEnglish: "The supremely expanding one" },
  { id: 45, telugu: "కమలాసనసంస్తుతాయ", english: "Kamalasana Samsthutaya", meaningTelugu: "బ్రహ్మదేవునిచే స్తుతించబడినవాడు", meaningEnglish: "Praised by Brahma" },
  { id: 46, telugu: "ఏకవర్ణాయ", english: "Ekavarnaya", meaningTelugu: "ఏక వర్ణ స్వరూపుడు", meaningEnglish: "Of single color/nature" },
  { id: 47, telugu: "ద్వివర్ణాయ", english: "Dwivarnaya", meaningTelugu: "రెండు వర్ణాల స్వరూపుడు", meaningEnglish: "Of dual nature" },
  { id: 48, telugu: "త్రివర్ణాయ", english: "Trivarnaya", meaningTelugu: "మూడు వర్ణాల స్వరూపుడు", meaningEnglish: "Of three colors/natures" },
  { id: 49, telugu: "సుమనోహరాయ", english: "Sumanoharaya", meaningTelugu: "అందమైన రూపం కలవాడు", meaningEnglish: "The beautiful one" },
  { id: 50, telugu: "చతుర్వర్ణాయ", english: "Chatur Varnaya", meaningTelugu: "నాలుగు వర్ణాల స్వరూపుడు", meaningEnglish: "Of four natures" },
  { id: 51, telugu: "పంచవర్ణాయ", english: "Pancha Varnaya", meaningTelugu: "ఐదు వర్ణాల స్వరూపుడు", meaningEnglish: "Of five colors/natures" },
  { id: 52, telugu: "ప్రజాపతయే", english: "Prajapathaye", meaningTelugu: "ప్రజల పాలకుడు", meaningEnglish: "Lord of creation" },
  { id: 53, telugu: "అహర్పతయే", english: "Ahaspathaye", meaningTelugu: "దినాలకు అధిపతి", meaningEnglish: "Lord of the day" },
  { id: 54, telugu: "అగ్నిగర్భాయ", english: "Agni Garbhaya", meaningTelugu: "అగ్ని గర్భంలో పుట్టినవాడు", meaningEnglish: "Born in fire's womb" },
  { id: 55, telugu: "శమీగర్భాయ", english: "Sami Garbhaya", meaningTelugu: "శమీ వృక్షం నుండి పుట్టినవాడు", meaningEnglish: "Born from Shami tree" },
  { id: 56, telugu: "విశ్వరేతసే", english: "Viswa Reythase", meaningTelugu: "విశ్వానికి బీజం", meaningEnglish: "Seed of the universe" },
  { id: 57, telugu: "సురారిఘ్నే", english: "Surarighne", meaningTelugu: "దేవతల శత్రువులను సంహరించేవాడు", meaningEnglish: "Slayer of enemies of gods" },
  { id: 58, telugu: "హరిద్వర్ణాయ", english: "Haridh Varnaya", meaningTelugu: "పచ్చని రంగు కలవాడు", meaningEnglish: "Of green complexion" },
  { id: 59, telugu: "శుభకరాయ", english: "Shubhakaraya", meaningTelugu: "శుభం కలిగించేవాడు", meaningEnglish: "Bestower of auspiciousness" },
  { id: 60, telugu: "పటవే", english: "Vatave", meaningTelugu: "చురుకైనవాడు", meaningEnglish: "The agile one" },
  { id: 61, telugu: "వటువేషభృతే", english: "Vatuvesha Bruthey", meaningTelugu: "బ్రహ్మచారి వేషం ధరించినవాడు", meaningEnglish: "One dressed as a celibate student" },
  { id: 62, telugu: "పూషాయ", english: "Pushney", meaningTelugu: "పోషించేవాడు", meaningEnglish: "The nourisher" },
  { id: 63, telugu: "గభస్తయే", english: "Gabhastaye", meaningTelugu: "కిరణాల వంటివాడు", meaningEnglish: "Radiant like sun rays" },
  { id: 64, telugu: "గహనాయ", english: "Gahanaya", meaningTelugu: "లోతైనవాడు, అర్థం చేసుకోలేనివాడు", meaningEnglish: "The profound, inscrutable one" },
  { id: 65, telugu: "చంద్రవర్ణాయ", english: "Chandra Varnaya", meaningTelugu: "చంద్రుని రంగు కలవాడు", meaningEnglish: "Of moon-like complexion" },
  { id: 66, telugu: "కళాధరాయ", english: "Kaladharaya", meaningTelugu: "కళలను ధరించినవాడు", meaningEnglish: "Bearer of all arts" },
  { id: 67, telugu: "మాయాధరాయ", english: "Mayaadharaya", meaningTelugu: "మాయను ధరించినవాడు", meaningEnglish: "Master of illusion" },
  { id: 68, telugu: "మహామాయినే", english: "Maha Mayuthe", meaningTelugu: "మహా మాయావి", meaningEnglish: "The great illusionist" },
  { id: 69, telugu: "కైవల్యాయ", english: "Kaivalyaya", meaningTelugu: "మోక్షం ప్రసాదించేవాడు", meaningEnglish: "Bestower of liberation" },
  { id: 70, telugu: "శంకరాత్మజాయ", english: "Shankarathmajaya", meaningTelugu: "శంకరుని ఆత్మజుడు", meaningEnglish: "Soul of Shankara" },
  { id: 71, telugu: "విశ్వయోనయే", english: "Viswayonaye", meaningTelugu: "విశ్వానికి మూలం", meaningEnglish: "Source of the universe" },
  { id: 72, telugu: "అమేయాత్మనే", english: "Ameyathmaya", meaningTelugu: "కొలవలేని ఆత్మ కలవాడు", meaningEnglish: "Of immeasurable soul" },
  { id: 73, telugu: "తేజోనిధయే", english: "Tejo Nidhaye", meaningTelugu: "తేజస్సు నిధి", meaningEnglish: "Treasury of brilliance" },
  { id: 74, telugu: "అనామయాయ", english: "Anamayaya", meaningTelugu: "వ్యాధి రహితుడు", meaningEnglish: "The diseaseless one" },
  { id: 75, telugu: "పరమేష్ఠినే", english: "Parameshtine", meaningTelugu: "పరమాత్ముడు", meaningEnglish: "The supreme being" },
  { id: 76, telugu: "పరబ్రహ్మణే", english: "Parabrahmane", meaningTelugu: "పరబ్రహ్మ స్వరూపుడు", meaningEnglish: "Form of supreme Brahman" },
  { id: 77, telugu: "వేదగర్భాయ", english: "Veda Garbhaya", meaningTelugu: "వేదాల సారాంశం", meaningEnglish: "Essence of Vedas" },
  { id: 78, telugu: "విరాట్సుతాయ", english: "Virat Suthaya", meaningTelugu: "విరాట్ పురుష కుమారుడు", meaningEnglish: "Son of cosmic being" },
  { id: 79, telugu: "పుళిందకన్యాభర్త్రే", english: "Pulinda Kanya Bharthaya", meaningTelugu: "వల్లీ దేవికి భర్త", meaningEnglish: "Husband of Valli" },
  { id: 80, telugu: "మహాసారస్వతావృతాయ", english: "Mahasaraswatha Vruthaya", meaningTelugu: "సరస్వతి దేవితో ఉండేవాడు", meaningEnglish: "Surrounded by great wisdom" },
  { id: 81, telugu: "ఆశ్రితాఖిలదాత్రే", english: "Aasrithakila Dhatrey", meaningTelugu: "శరణు వచ్చిన వారికి సర్వం ఇచ్చేవాడు", meaningEnglish: "Giver of everything to devotees" },
  { id: 82, telugu: "చోరఘ్నాయ", english: "Choraghnaya", meaningTelugu: "దొంగలను నాశనం చేసేవాడు", meaningEnglish: "Destroyer of thieves" },
  { id: 83, telugu: "రోగనాశనాయ", english: "Roga Nasanaya", meaningTelugu: "రోగాలను నాశనం చేసేవాడు", meaningEnglish: "Destroyer of diseases" },
  { id: 84, telugu: "అనంతమూర్తయే", english: "Anantha Murthaye", meaningTelugu: "అనంత రూపాలు కలవాడు", meaningEnglish: "Of infinite forms" },
  { id: 85, telugu: "ఆనందాయ", english: "Anandaya", meaningTelugu: "ఆనంద స్వరూపుడు", meaningEnglish: "Embodiment of bliss" },
  { id: 86, telugu: "శిఖిండికృతకేతనాయ", english: "Shikhandiney Kritha Kethanaya", meaningTelugu: "నెమలి ఈకను ధ్వజంగా కలవాడు", meaningEnglish: "One with peacock feather flag" },
  { id: 87, telugu: "డంభాయ", english: "Dambhaya", meaningTelugu: "ప్రభావవంతుడు", meaningEnglish: "The majestic one" },
  { id: 88, telugu: "పరమడంభాయ", english: "Parama Dambhaya", meaningTelugu: "అత్యంత ప్రభావవంతుడు", meaningEnglish: "The supremely majestic" },
  { id: 89, telugu: "మహాడంభాయ", english: "Maha Dambhaya", meaningTelugu: "మహా ప్రభావవంతుడు", meaningEnglish: "The greatly majestic" },
  { id: 90, telugu: "వృషాకపయే", english: "Vrusha Kapaye", meaningTelugu: "వృషభం మరియు కపి స్వరూపుడు", meaningEnglish: "Form of bull and monkey" },
  { id: 91, telugu: "కారణోత్పత్తిదేహాయ", english: "Karanopattha Dehaya", meaningTelugu: "కారణ దేహం కలవాడు", meaningEnglish: "One with causal body" },
  { id: 92, telugu: "కారణాతీతవిగ్రహాయ", english: "Karanaateetha Vigrahaya", meaningTelugu: "కారణానికి అతీతమైన రూపం కలవాడు", meaningEnglish: "Beyond causal form" },
  { id: 93, telugu: "అనీశ్వరాయ", english: "Aneeshwaraya", meaningTelugu: "స్వతంత్రుడు", meaningEnglish: "The independent one" },
  { id: 94, telugu: "అమృతాయ", english: "Amruthaya", meaningTelugu: "అమరుడు", meaningEnglish: "The immortal one" },
  { id: 95, telugu: "ప్రాణాయ", english: "Pranaya", meaningTelugu: "ప్రాణ స్వరూపుడు", meaningEnglish: "Embodiment of life force" },
  { id: 96, telugu: "ప్రాణాయామపరాయణాయ", english: "Pranayama Parayanaya", meaningTelugu: "ప్రాణాయామానికి దేవుడు", meaningEnglish: "Lord of pranayama" },
  { id: 97, telugu: "విరుద్ధహంత్రే", english: "Viruddha Hanthre", meaningTelugu: "శత్రువులను సంహరించేవాడు", meaningEnglish: "Slayer of opponents" },
  { id: 98, telugu: "వీరఘ్నాయ", english: "Veeraghnaya", meaningTelugu: "వీరులను జయించేవాడు", meaningEnglish: "Conqueror of heroes" },
  { id: 99, telugu: "రక్తాస్యాయ", english: "Raktha-shyama Kalaya", meaningTelugu: "ఎరుపు రంగు ముఖం కలవాడు", meaningEnglish: "Red-faced one" },
  { id: 100, telugu: "శ్యామకంధరాయ", english: "Shyama Kandharaya", meaningTelugu: "నల్లని కంఠం కలవాడు", meaningEnglish: "Dark-throated one" },
  { id: 101, telugu: "సుబ్రహ్మణ్యాయ", english: "Subrahmanyaya", meaningTelugu: "బ్రాహ్మణులకు శుభం కలిగించేవాడు", meaningEnglish: "Auspicious to Brahmanas" },
  { id: 102, telugu: "ప్రీతాయ", english: "Preethaya", meaningTelugu: "ప్రసన్నుడు", meaningEnglish: "The pleased one" },
  { id: 103, telugu: "బ్రహ్మణ్యాయ", english: "Brahmanyaya", meaningTelugu: "బ్రహ్మ స్వరూపుడు", meaningEnglish: "Of Brahman nature" },
  { id: 104, telugu: "బ్రాహ్మణప్రియాయ", english: "Brahmanapriyaya", meaningTelugu: "బ్రాహ్మణులకు ప్రియమైనవాడు", meaningEnglish: "Dear to Brahmanas" },
  { id: 105, telugu: "వంశవృద్ధికరాయ", english: "Vamshavruddhi Karaya", meaningTelugu: "వంశం వృద్ధి చేసేవాడు", meaningEnglish: "One who increases lineage" },
  { id: 106, telugu: "వేదవేద్యాయ", english: "Vedavedhyaya", meaningTelugu: "వేదాల ద్వారా తెలిసేవాడు", meaningEnglish: "Known through Vedas" },
  { id: 107, telugu: "అక్షయఫలప్రదాయ", english: "Akshaya Phalapradaya", meaningTelugu: "నశించని ఫలితాలు ఇచ్చేవాడు", meaningEnglish: "Giver of imperishable fruits" },
  { id: 108, telugu: "మయూరవాహనాయ", english: "Mayuravahana", meaningTelugu: "నెమలిని వాహనంగా కలవాడు", meaningEnglish: "One who rides the peacock" }
];

const App = () => {
  return null;
};

export default App;
